POST https://shark-app-h7hqz.ondigitalocean.app/api/send_message 
Content-Type: application/json 
Authorization: Bearer EAAdSuoYbd24BO3hcorKmvrA2nzkSr0NMjk9b7EeuX1soXqwuxrEJzwlbOVG0rXQIj40IGBhE7bVzgZA07RsRuWPurBoLuQUODA5nK8HbEzZCKtTWXpWWnmS0tdeaizuj6KcrRdtbKBhbyL1PKomj1LkNPm9MhM30P5BHrUZCoEj1mxb4473O2HCnJO1fb7gVApx6iB0QoS0ZCLv5qRLhfXVGXOWncPE9Qt0ZD

{
    "message": "hello how are you!", 
    "number": "+919579833281"
}