POST https://graph.facebook.com/v21.0/474660259071346/messages 
Content-Type: application/json 
Authorization: Bearer EAAdSuoYbd24BO6rMUi24eWtSmFyJhVe7F4YhcMsAYu6WIeVXBhNVEkRUGAbhXcoZA0ZAgWOpCVLbO6v0lyMgarGbwNoBwbtl4eSI5gGT3bHuLASZCdZB3UZBnaiFI7xfyqFXtYhNDbtC74sZCW1eMJuGGYDjLWYCSPXFdfFLUnX5pDyY5kjL82DhDEh5TvvUgYkA1EjVyCF3ZA7i7Hi9biErBPSU5AdyKTOj0AZD

{
  "messaging_product": "whatsapp",
  "recipient_type": "individual",
  "to": "+919579833281",
  "type": "text",
  "text": {
    "body": "Pitch perfect."
  }
}