POST https://graph.facebook.com/v21.0/474660259071346/messages 
Content-Type: application/json 
Authorization: Bearer EAAdSuoYbd24BOZCq6oGYZCLV5FIDk8VNqfyiCjDnoah7ZCmG1Srks8OIylH1tRwTsXEWZC64iCjdaa1FaQqB55UGBhJs6CVhYYrZB0ZAVpxnQPfvUnRR48LZB2ektWvN1oZCrGOxPmvyWDjMdHOJkiZBbqCuF9pyY4gJ8qpZAexHHn8hS3Y6x4ZAERIAx1aGdMsBGj8VGKX1tZCSujcIbSBZA0tMzLLrYJe2tPJndOQQZD

{
  "messaging_product": "whatsapp",
  "recipient_type": "individual",
  "to": "+919579833281",
  "type": "text",
  "text": {
    "body": "Pitch perfect."
  }
}