name: Build and deploy 

on:
    push:
      branches:
        - master
    workflow_dispatch: 

jobs: 
    build: 
        runs-on: ubuntu-latest 
        steps:
            - uses: actions/checkout@v4
            - name: setup python 
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'
            
            - name: Create and start virtual environment
              run: |
                    python -m venv venv
                    source venv/bin/activate
    
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Zip artifact for deployment
              run: zip release.zip ./* -r

            - name: Upload artifact for deployment jobs
              uses: actions/upload-artifact@v4
              with:
                name: python-app
                path: |
                    release.zip
                    !venv/
